language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
# We do support Node.js v4 but tests are not run against it anymore since the testing frameworks do not support it anymore.
#  - "4"
  - "6"
  - "8"
  - "10"
  - "11"
install:
  - npm install
  - npm install hiredis
after_success:
  - CODECLIMATE_REPO_TOKEN=c60100f656e32c1003fec9b96c4aba47fd4c190069931763ac1879aa2ef28398 node ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
