name: Benchmarking

on: [push]

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i --no-audit --prefer-offline
      - name: Run Benchmark
        run: npm run benchmark        
