name: Benchmarking

on: [push]

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i --no-audit --prefer-offline
      - name: Run Benchmark
        run: npm run benchmark > benchmark-output.txt && cat benchmark-output.txt
      - name: Upload Benchmark Result
        uses: actions/upload-artifact@v1
        with:
          name: benchmark-output.txt
          path: benchmark-output.txt

      - name: Store Node.js ${{ matrix.node-version }} benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Node.js ${{ matrix.node-version }} Benchmark
          tool: 'benchmarkjs'
          output-file-path: benchmark-output.txt
